### ISSUE TITLE
digitisation processor

### ISSUE THREAD

**Issue by airqui** [SiWECAL-TestBeam/SiWECAL-Sim#1]
Hi @fabriciojm 
could you put in processors/ the processors for the digitisation ? 
Creting the src/ include/ folders + the CMakeList.txt

Thanks!
Adrián

**Comment by fabriciojm** [comment]
Hi @airqui, it's done in [my forked repo](https://github.com/fabriciojm/SiWECAL-Sim). I've put the working version I have under my `CaliceInstall/calice_sim/digitization` installation, so there's quite a lot of (easy) cleaning to do there to have it run "standalone" - will do next week. Once I finish up some work in the generation, I'll do a PR.
