### ISSUE TITLE
Names and defaults for SIM-build

### ISSUE THREAD

**Issue by kunathj** [SiWECAL-TestBeam/SiWECAL-Sim#4]
@fabriciojm Some naming conventions changed with https://github.com/SiWECAL-TestBeam/SiWECAL-TB-analysis/pull/34.

- [x] drop `bcid_prev`, `bcid_next`, `sum_hg`
- [x] `hit_lg`→`hit_adc_low` _default to:_ Use this however you want. Integer
- [x] `hit_hg`→`hit_adc_high` _default to:_ Use this however you want. Integer
- [x] `event`_default to:_ -1. Or actually use it as an event counter. Integer
- [x] `spill` _default to:_ -1. Integer
- [x] `cycle`  _default to:_ -1. Integer
- [x] `bcid`  _default to:_ -1. Integer
- [x] `bcid_first_sca_full`  _default to:_ -999 (this is the value taken if this does not happen). Integer
- [x] `bcid_merge_end`  _default to:_ same value as bcid. Integer
- [x] `id_run`  _default to:_ -1. Integer
- [x] `id_dat`  _default to:_ -1. Integer
- [x] `nhit_slab`  _default to:_ 15. Integer
- [x] `nhit_chip`  _default to:_ 15*16. Integer
- [x] `nhit_chan`  _default to:_ `15*16*64`. But much better if you would actually fill it with the proper value. Integer
- [x] `nhit_len`  _default to:_ same as `nhit_chan`. Integer
- [x] `sum_energy`  _default to:_ -1 But much better if you would actually fill it with the proper value. Float
- [x] `sum_energy_lg`  _default to:_ same as `sum_energy`. Float
- [x] `hit_slab`  _default to:_ -1. Integer
- [x] `hit_chip`  _default to:_ -1. Integer
- [x] `hit_chan`  _default to:_ -1. Integer
- [x] `hit_sca`  _default to:_ -1. Integer
- [x] `hit_x`  This you have for sure. Float
- [x] `hit_y`  This you have for sure. Float
- [x] `hit_z`  This you have for sure. Float
- [x] `hit_x`  This you have for sure. Float
- [x] `hit_energy` This you have for sure. I believe this should be in units of MIP. Float
- [x] `hit_energy_lg` For simulation, can be same as `hit_energy` (until you have the appropriate digitisation). Float
- [x] `hit_n_scas_filled`  _default to:_ 1. Integer
- [x] `hit_isHit`  _default to:_ 1. Integer
- [x] `hit_isMasked`  _default to:_ 0. Integer
- [x] `hit_isCommissioned`  _default to:_ 1. Integer

I put `-1` wherever I don't care about the values. For the other fields, I have preferences for the default values. Those new default values would simplify using the SIM-build files as a drop-in replacement for the data-build files in analysis code.

Wherever possible, it is of course preferable to put the true value (e.g. for `ǹhit_slab` and a shower that depletes within the calorimeter).

**Comment by fabriciojm** [comment]
Hi @kunathj, in [my last commit](https://github.com/fabriciojm/SiWECAL-Sim/commit/0932dae87eab1aea9d5d096650257dfc950fcd7f) (still need to PR to main), this implementation is done now for the sim build tree. A few comments:
- `hit_adc_low` and `hit_adc_high` default to `-1` (was also the case before updating the names).
- `event` is an event counter
- `nhit_slab` stores the actual value of number of slabs hit; and `nhit_chip` and `nhit_chan` now defaults to the value you suggest, but why do we want to default to the maximum in these three?
- `nhit_len` stores the proper value
- `sum_energy` stores the vale in Geant4 "GeV", if the lcio->root is taken from sim before conversion and in MIPs if done after.
- `hit_slab` stores the proper value.
- `hit_sca` defaults to `-1`, I suppose the second time you mention it (ask to default to `1`) is a typo

**Comment by kunathj** [comment]
The second mention of `hit_sca` was supposed to be `hit_n_scas_filled`. I edited it to the correct name now.

Reasoning for defaulting to the maximum value: I expect these `nhit_*` variables to be used for good-event-selections (I have used `nhit_slab` and `nhit_chip` for this purpose myself). You can imagine a scenario where some chips are not as efficient as others. Then requiring a minimum number of chips in the event will throw away events where too many of the chips are missing.

If it is simple enough for you, filling the proper values is of course better than using the maximum. But the maximum ensures that the simulated events pass the minimum-selections. And thus a minimum-selection can be used with both data and simulation without the need to change any code.

**Comment by fabriciojm** [comment]
Thanks, I understand. I've checked all the items in the initial list as they are either filling the proper value or defaulting to what you suggested, and leave below a new to-do list:
- Once the mapping is included/handled as a steering parameter in the lcio->build conversion, fill the proper values of:
- [x] `hit_chip` and `nhit_chip`.
- [x] `hit_chan` and `nhit_chan`.
- Once (low gain) digitization is in place, fill:
- [x] `hit_energy_lg` and `sum_energy_lg`.

**Comment by kunathj** [comment]
Do you want to keep track of these (two) new improvement suggestions from this issue, or have dedicated issues for them?
From my side, the issue is solved, and I would have been ok with closing it.

**Comment by fabriciojm** [comment]
Let's keep it open until I implement the mapping, thanks.

**Comment by fabriciojm** [comment]
`(n)hit_{chip,chan}` properly mapped in build files now. I'll close this and leave the `hit_energy_lg` and `sum_energy_lg` in another digi issue.
